//*******SEAMLESS INTEGRATION*******//

var express = require('express');
var bodyParser = require('body-parser');
var app = express();
var path = require('path');
var request = require("request");
var EventEmitter = require("events").EventEmitter;
var IPN = new EventEmitter();
var urlencodedParser = bodyParser.urlencoded({extended: true});
var md5 = require('md5');

app.use(bodyParser.json());

app.use('/css', express.static(path.join(__dirname, 'css')));
app.use('/images', express.static(path.join(__dirname, 'images')));


var merchant_id = "";//Insert merchant id here
var orderid = ""; // Order ID should be random generated by merchant function
var vkey = "**********"; //Replace ********** with your MOLPay verification_Key
var URL;


//****MANDATORY VARIABLES********//
var Default = 1;//Default value, DO NOT CHANGE
var treq = 1; // Default value, DO NOT CHANGE
var status;
var mpsmerchantid;
var mpschannel;
var mpsamount;
var mpsorderid;
var  mpsbill_name;
var  mpsbill_email;
var  mpsbill_mobile;
var  mpsbill_desc;
var  mpscountry;
var  mpsvcode;
var  mpscurrency;
var  mpslangcode;
var mpstimer;
var mpstimerbox;
var mpscancelurl;
var mpsreturnurl;
var mpsapiversion;

// The '/' below reads from the main directory where your project is at. Just make sure your codes are in the same folder or directory
app.get('/',  function(req, res) {
    res.sendFile(path.join(__dirname + '/index.html'));// Opens your main html file
});

//Variables are stored in function to prevent callback of response twice
function MolPayObj(req,res){
    if(Default == 1){
        status = true;// Set True to proceed with MOLPay
        mpsmerchantid = merchant_id;
        mpschannel = req.body.payment_options;
        mpsamount = req.body.total_amount;
        mpsorderid = orderid; //Order ID should be a random generated value by merchant
        mpsbill_name = req.body.billingFirstName + " " + req.body.billingLastName;
        mpsbill_email = req.body.billingEmail;
        mpsbill_mobile = req.body.billingMobile;
        mpsbill_desc = req.body.billingAddress;
        mpscountry  = "MY";
        mpsvcode  = md5(req.body.total_amount + merchant_id + orderid + vkey);
        mpscurrency = req.body.currency;
        mpslangcode = "en";
        mpstimer = req.body.molpaytimer;
        mpstimerbox = "#counter";
        mpsreturnurl = "http://127.0.0.1:8080/returnurl"; // Enter your return url here
        mpscancelurl = "http://127.0.0.1:8080/cancelurl"; // Enter your cancel url here
        mpsapiversion = "3.16"; //**NOTE:  For production use 3.17 / Sandbox use 3.16

        //The following response codes are used to display the output in '/returnurl'  and in the console
        //This can also be used as a receipt, you can change the way the output is displayed if you like
        response = {

            status,
            mpsmerchantid,
            mpschannel ,
            mpsamount,
            mpsorderid ,
            mpsbill_name,
            mpsbill_email,
            mpsbill_mobile,
            mpsbill_desc ,
            mpscountry  ,
            mpsvcode  ,
            mpscurrency,
            mpslangcode ,
            mpstimer ,
            mpstimerbox,
            mpscancelurl,
            mpsreturnurl,
            mpsapiversion
        };

        console.log(response);

        //convert the response in JSON format and print it to '/returnurl'
        res.send(JSON.stringify(response));

        Default = Default + 1; // DO NOT CHANGE THIS. This is to ensure the entire function won't be called twice
    }else
    {
        res.send(JSON.stringify(response));
    }

}

//Handles post data, a directory '/returnurl' is created to receive post data
//Make sure you have a hidden input in your main html that includes your return url link
//The '/returnurl' below can be changed to your own return url link name/directory
//This is the same if you want to use it for your callback url

app.post('/returnurl', urlencodedParser, function(req, res){
    MolPayObj(req,res); // Calls function to handle post data
});

//To handle cancel request
app.post('/cancelurl', urlencodedParser, function(req, res){
    res.send("You have cancelled order. Thank you");
});

var server = app.listen(8080, '127.0.0.1',function(){
    var host = server.address().address;
    var port = server.address().port;
    console.log("Example app listening at http://%s:%s", host, port);
});
